### ISSUE TITLE
Google action dialogflow fullfilment webhook call accessToken is not present in request headers( reagrding issue #394)

### ISSUE THREAD

**Issue by amiya-elear** [actions-on-google/actions-on-google-nodejs#395] opened 2020-06-09 06:23 UTC
Question regarding issue #394 (closed)
Thanks fleker for your response, But I read one official document it says that "user's third-party OAuth 2 accessToken is sent in the Authorization header when smart home intents are sent to your fulfillment". my question is there any way to get accessToken in request headers or any configuration to send it in the request headers?
official Doc: https://developers.google.com/assistant/smarthome/concepts/fulfillment-authentication

**Comment by Fleker** [comment] 2020-06-09 15:40
This is a duplicate of #394. Let's continue the conversation there.

**Closed** 2020-06-09 15:40 UTC
Labels: duplicate
