### ISSUE TITLE
"Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by VikasNS** [actions-on-google/actions-on-google-nodejs#236] opened 2018-10-14 18:31 UTC
Response:
{
  "errorMessage": "Cannot convert undefined or null to object",
  "errorType": "TypeError",
  "stackTrace": [
    "Function.keys (<anonymous>)",
    "Lambda.<anonymous> (/var/task/node_modules/actions-on-google/dist/framework/lambda.js:36:36)",
    "Generator.next (<anonymous>)",
    "/var/task/node_modules/actions-on-google/dist/framework/lambda.js:22:71",
    "new Promise (<anonymous>)",
    "__awaiter (/var/task/node_modules/actions-on-google/dist/framework/lambda.js:18:12)",
    "/var/task/node_modules/actions-on-google/dist/framework/lambda.js:30:46",
    "omni (/var/task/node_modules/actions-on-google/dist/assistant.js:44:53)"
  ]
}

**Comment by Canain** [comment] 2018-10-15 22:14
This looks like a duplicate of #219

**Closed** 2018-10-15 22:14 UTC
Labels: duplicate
