### ISSUE TITLE
Connection failed to Google Actions

### ISSUE THREAD

**Issue by AngelLuisSanchez** [actions-on-google/actions-on-google-nodejs#159] opened 2018-05-21 12:12 UTC
Hi!
I am not able to connect and integrate to Google Actions when I set Auth0 parameters.
I'm following [this tutorial](https://www.jovo.tech/blog/google-action-account-linking-auth0/) but not works to me :(

I want to authenticate the user and know some user's attributes such as email and username.

Before I set Auth0 server, Google Actions works fine (without authentication).
This is the error that Google Actions shows;
"It looks like your my test app account is not linked yet".

What is more, I can't integrate with Google Assistant from DialogFlow.

![image](https://user-images.githubusercontent.com/9683844/40306959-f4e03ba2-5d00-11e8-8c1a-40b7b5908e41.png)

I use dialogflow V2 and [jovo ](https://www.jovo.tech/framework/docs/)to deploy.

Any idea?

**Comment by Phaael** [comment] 2018-05-21 17:48
for me usually the authentication process does not work in Simulator, so I do this in on device to test and the google-account into device and simulator must be the same

**Comment by AngelLuisSanchez** [comment] 2018-05-22 07:47
Thanks for your response!

If I go to Google actions directly, test de application and debug in Chrome, it shows this logs:

`[["simulate_res","It looks like your test app account is not linked yet.",null,"....","....",[null,null,[["Account Linking Url","https://assistant.google.com/services/auth/handoffs/auth/start?account_name\u003dEMAIL\u0026provider\u003PROJECT_ID\u0026scopes\u003dLIST_SCOPES\u0026authuser\u003d0\u0026return_url\u003dhttps://www.google.com/"]`

The _Account Linking Url_ is MalFormed. If I replace unicode characteres in the URL, I've got this =>
`https://assistant.google.com/services/auth/handoffs/auth/start?account_name=EMAIL&provider=PROJECT_ID&scopes=LIST_SCOPES&authuser=0&return_url=https://www.google.com/`

I don't know if this is the real issue.

**Comment by anmolagar** [comment] 2018-05-24 22:54
Yeah, same issue.. I tried connecting with support team but no proper answers.
This is a BLOCKER for me as i cannot update the intents in AoG and account linking is not working.

**Comment by Canain** [comment] 2018-09-15 00:16
Can you still reproduce this issue?

**Comment by Canain** [comment] 2019-03-25 19:22
Closing since there hasn't been any more comments.

**Closed** 2019-03-25 19:21 UTC
Labels: platform issue
